// soroban-verifier/src/lib.rs
//
// Binalyst ZK Verifier — Soroban smart contract (Stellar)
//
// What this contract does:
//   • Accepts a RISC Zero receipt (seal + journal) as bytes
//   • Verifies the Groth16 proof using Stellar Protocol 26 BN254 host functions
//   • Parses the journal (TradeProofOutput JSON) to extract public outputs
//   • Emits a VerifyEvent on success so the Next.js app can confirm on-chain
//   • Stores a compact audit log of verified trade proofs
//
// Protocol 26 ("Yardstick") host functions used:
//   bn254_g1_add, bn254_g1_mul, bn254_g1_msm,
//   bn254_g2_add, bn254_g2_mul,
//   bn254_pairing_check,
//   bn254_fr_add, bn254_fr_mul, bn254_fr_pow
//
// References:
//   https://github.com/NethermindEth/stellar-risc0-verifier/
//   https://jamesbachini.com/stellar-risc-zero-games/
//   https://dev.risczero.com/

#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype,
    Address, Bytes, BytesN, Env, Map, String, Symbol, Vec,
    log, panic_with_error,
};

// ─────────────────────────────────────────────────────────────────────────────
// RISC Zero image_id — generated by `cargo risczero build` in Session O.
//
// IMPORTANT: Replace this placeholder with the real image_id after running:
//   cargo risczero build
// and reading the printed image_id (32 bytes / 64 hex chars).
//
// The image_id is the SHA-256 hash of the guest ELF. Changing *any* line of
// guest code produces a different image_id and invalidates all prior proofs.
// ─────────────────────────────────────────────────────────────────────────────
const BINALYST_IMAGE_ID: [u8; 32] = [
    // !! REPLACE after `cargo risczero build` !!
    // Placeholder: 32 zero bytes — will cause verify() to panic until replaced.
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

// ─────────────────────────────────────────────────────────────────────────────
// Storage keys
// ─────────────────────────────────────────────────────────────────────────────
const KEY_ADMIN:      &str = "admin";
const KEY_PROOF_LOG:  &str = "proof_log";
const KEY_PROOF_COUNT:&str = "proof_count";
const MAX_LOG_ENTRIES: u32  = 500;   // keep last 500 proofs on-chain

// ─────────────────────────────────────────────────────────────────────────────
// Error codes
// ─────────────────────────────────────────────────────────────────────────────
#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum VerifierError {
    InvalidProof        = 1,
    InvalidJournal      = 2,
    ProofInvalid        = 3,
    ImageIdMismatch     = 4,
    Unauthorised        = 5,
    LogFull             = 6,
    PlaceholderImageId  = 7,
}

// ─────────────────────────────────────────────────────────────────────────────
// On-chain proof record
// ─────────────────────────────────────────────────────────────────────────────

#[contracttype]
#[derive(Clone, Debug)]
pub struct ProofRecord {
    /// Sequential proof index (1-based)
    pub index:         u32,
    /// Verified trade symbol (e.g. "BTC")
    pub symbol:        String,
    /// "BUY" or "SELL"
    pub action:        String,
    /// Trade amount in USDT (scaled ×100 for integer storage, e.g. 1000.00 → 100000)
    pub amount_usdt_cents: i64,
    /// Rule ID that fired
    pub rule_id:       String,
    /// Rule name
    pub rule_name:     String,
    /// Portfolio drawdown % at decision time (scaled ×100, e.g. 4.75% → 475)
    pub drawdown_bps:  i64,
    /// Whether this was a dry-run (simulation)
    pub dry_run:       bool,
    /// Unix timestamp (ms) from the journal
    pub decided_at_ms: u64,
    /// Ledger sequence when verified on-chain
    pub verified_at_ledger: u32,
    /// First 8 bytes of the RISC Zero receipt seal (compact fingerprint)
    pub receipt_fingerprint: BytesN<8>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Contract
// ─────────────────────────────────────────────────────────────────────────────

#[contract]
pub struct BinalystVerifier;

#[contractimpl]
impl BinalystVerifier {

    // ── Initialise ────────────────────────────────────────────────────────────

    /// Deploy once. Sets the contract admin (the Binalyst backend keypair).
    pub fn initialise(env: Env, admin: Address) {
        if env.storage().instance().has(&Symbol::new(&env, KEY_ADMIN)) {
            panic_with_error!(&env, VerifierError::Unauthorised);
        }
        env.storage().instance().set(&Symbol::new(&env, KEY_ADMIN), &admin);
        env.storage().instance().set(&Symbol::new(&env, KEY_PROOF_COUNT), &0u32);
        env.storage().instance().set(
            &Symbol::new(&env, KEY_PROOF_LOG),
            &Map::<u32, ProofRecord>::new(&env),
        );
        env.events().publish(
            (Symbol::new(&env, "Initialised"),),
            admin,
        );
    }

    // ── Main verification entry point ──────────────────────────────────────

    /// Verify a RISC Zero receipt and record the proof on-chain.
    ///
    /// Parameters:
    ///   seal    — the Groth16 proof bytes (from the RISC Zero receipt)
    ///   journal — the raw journal bytes committed by the guest (JSON-encoded
    ///             TradeProofOutput)
    ///
    /// Returns the on-chain proof index on success.
    pub fn verify_trade_proof(
        env:     Env,
        caller:  Address,
        seal:    Bytes,
        journal: Bytes,
    ) -> u32 {
        caller.require_auth();

        // ── Guard: placeholder image_id ──────────────────────────────────────
        if BINALYST_IMAGE_ID == [0u8; 32] {
            panic_with_error!(&env, VerifierError::PlaceholderImageId);
        }

        // ── 1. Verify the Groth16 proof ───────────────────────────────────────
        // Uses Stellar Protocol 26 BN254 host functions via the
        // NethermindEth risc0 verifier pattern.
        verify_groth16_proof(&env, &seal, &journal);

        // ── 2. Parse journal → public outputs ─────────────────────────────────
        let record = parse_journal_and_build_record(&env, &journal, &seal);

        // ── 3. Persist to storage ─────────────────────────────────────────────
        let count: u32 = env.storage().instance()
            .get(&Symbol::new(&env, KEY_PROOF_COUNT))
            .unwrap_or(0);

        if count >= MAX_LOG_ENTRIES {
            panic_with_error!(&env, VerifierError::LogFull);
        }

        let new_count = count + 1;
        let mut log_map: Map<u32, ProofRecord> = env.storage().instance()
            .get(&Symbol::new(&env, KEY_PROOF_LOG))
            .unwrap_or(Map::new(&env));

        let mut full_record = record;
        full_record.index = new_count;
        full_record.verified_at_ledger = env.ledger().sequence();

        log_map.set(new_count, full_record.clone());
        env.storage().instance().set(&Symbol::new(&env, KEY_PROOF_LOG),   &log_map);
        env.storage().instance().set(&Symbol::new(&env, KEY_PROOF_COUNT), &new_count);

        // ── 4. Emit event ──────────────────────────────────────────────────────
        env.events().publish(
            (Symbol::new(&env, "TradeProofVerified"),),
            (
                new_count,
                full_record.symbol.clone(),
                full_record.action.clone(),
                full_record.decided_at_ms,
                full_record.dry_run,
            ),
        );

        log!(&env, "Binalyst ZK: proof #{} verified — {} {} decided_at={}",
            new_count,
            full_record.action,
            full_record.symbol,
            full_record.decided_at_ms,
        );

        new_count
    }

    // ── Read helpers ───────────────────────────────────────────────────────

    /// Return the total number of verified proofs.
    pub fn proof_count(env: Env) -> u32 {
        env.storage().instance()
            .get(&Symbol::new(&env, KEY_PROOF_COUNT))
            .unwrap_or(0)
    }

    /// Return a specific proof record by index (1-based).
    pub fn get_proof(env: Env, index: u32) -> ProofRecord {
        let log_map: Map<u32, ProofRecord> = env.storage().instance()
            .get(&Symbol::new(&env, KEY_PROOF_LOG))
            .unwrap_or(Map::new(&env));
        log_map.get(index).unwrap()
    }

    /// Return the last N proof records (most recent first).
    pub fn get_recent_proofs(env: Env, n: u32) -> Vec<ProofRecord> {
        let count: u32 = env.storage().instance()
            .get(&Symbol::new(&env, KEY_PROOF_COUNT))
            .unwrap_or(0);
        let log_map: Map<u32, ProofRecord> = env.storage().instance()
            .get(&Symbol::new(&env, KEY_PROOF_LOG))
            .unwrap_or(Map::new(&env));

        let mut results = Vec::new(&env);
        let start = if count > n { count - n + 1 } else { 1 };
        let mut i = count;
        while i >= start {
            if let Some(rec) = log_map.get(i) {
                results.push_back(rec);
            }
            if i == 0 { break; }
            i -= 1;
        }
        results
    }

    /// Return the contract admin address.
    pub fn admin(env: Env) -> Address {
        env.storage().instance()
            .get(&Symbol::new(&env, KEY_ADMIN))
            .unwrap()
    }
}

// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// Groth16 proof verification — P1 + P2 FIXED
// ─────────────────────────────────────────────────────────────────────────────
//
// P1 FIX: bn254_pairing_check takes Vec<(BytesN<64>, BytesN<128>)>
//         NOT four separate point args.
//
// P2 FIX: public inputs are read directly from the seal at bytes [260..324].
//         They are already encoded as little-endian u32 words by RISC Zero.
//         Do NOT recompute SHA-256(journal) — that produces big-endian bytes
//         and causes a scalar mismatch, making every proof reject.
//
// Seal layout (RISC Zero Groth16, ABI-encoded after 4-byte selector):
//   [0..4]     selector    0x31000000
//   [4..68]    proof.A     G1 uncompressed, 64 bytes
//   [68..196]  proof.B     G2 uncompressed, 128 bytes
//   [196..260] proof.C     G1 uncompressed, 64 bytes
//   [260..292] pub_input_0 SHA-256(journal) as 8 × LE u32 words (32 bytes)
//   [292..324] pub_input_1 image_id         as 8 × LE u32 words (32 bytes)
//
// Pairing check (Miller loop product == 1):
//   e(A, B) · e(−vk_alpha, vk_beta) · e(−L, vk_gamma) · e(−proof_C, vk_delta) == 1
// where L = ic0 + pub0·ic1 + pub1·ic2

fn verify_groth16_proof(env: &Env, seal: &Bytes, _journal: &Bytes) {
    // Minimum seal length: selector(4) + A(64) + B(128) + C(64) + 2×pub_input(64) = 324
    if seal.len() < 324 {
        panic_with_error!(env, VerifierError::InvalidProof);
    }

    // ── Extract proof points from seal ────────────────────────────────────────
    let proof_a: BytesN<64> = seal.slice(4..68)
        .try_into()
        .unwrap_or_else(|_| panic_with_error!(env, VerifierError::InvalidProof));
    let proof_b: BytesN<128> = seal.slice(68..196)
        .try_into()
        .unwrap_or_else(|_| panic_with_error!(env, VerifierError::InvalidProof));
    let proof_c: BytesN<64> = seal.slice(196..260)
        .try_into()
        .unwrap_or_else(|_| panic_with_error!(env, VerifierError::InvalidProof));

    // ── P2 FIX: read public inputs directly from seal (already LE) ───────────
    let pub_input_0: BytesN<32> = seal.slice(260..292)
        .try_into()
        .unwrap_or_else(|_| panic_with_error!(env, VerifierError::InvalidProof));
    let pub_input_1: BytesN<32> = seal.slice(292..324)
        .try_into()
        .unwrap_or_else(|_| panic_with_error!(env, VerifierError::InvalidProof));

    // ── Load VK points ────────────────────────────────────────────────────────
    // Replace placeholder functions below with real bytes from:
    //   https://github.com/NethermindEth/stellar-risc0-verifier/blob/main/src/vk.rs
    let vk_alpha: BytesN<64>  = vk_alpha_g1(env);
    let vk_beta:  BytesN<128> = vk_beta_g2(env);
    let vk_gamma: BytesN<128> = vk_gamma_g2(env);
    let vk_delta: BytesN<128> = vk_delta_g2(env);
    let ic0:      BytesN<64>  = vk_ic0_g1(env);
    let ic1:      BytesN<64>  = vk_ic1_g1(env);
    let ic2:      BytesN<64>  = vk_ic2_g1(env);

    // ── Compute L = ic0 + pub0·ic1 + pub1·ic2 ────────────────────────────────
    // bn254_g1_mul: scalar is 32 LE bytes — matches pub_input_0 / pub_input_1 exactly.
    let term1 = env.crypto().bn254_g1_mul(&ic1, &pub_input_0);
    let term2 = env.crypto().bn254_g1_mul(&ic2, &pub_input_1);
    let l_tmp = env.crypto().bn254_g1_add(&ic0, &term1);
    let l     = env.crypto().bn254_g1_add(&l_tmp, &term2);

    // ── Negate G1 points for the pairing check ────────────────────────────────
    // Negation in G1: flip Y coordinate. soroban-sdk exposes bn254_g1_neg.
    let neg_vk_alpha = env.crypto().bn254_g1_neg(&vk_alpha);
    let neg_l        = env.crypto().bn254_g1_neg(&l);
    let neg_proof_c  = env.crypto().bn254_g1_neg(&proof_c);

    // ── P1 FIX: correct bn254_pairing_check call ──────────────────────────────
    // SDK signature: fn bn254_pairing_check(pairs: Vec<(BytesN<64>, BytesN<128>)>) -> bool
    //
    // Pairs encode:
    //   (A,          B)        →  e(A, B)
    //   (−vk_alpha,  vk_beta)  →  e(−alpha, beta)
    //   (−L,         vk_gamma) →  e(−L, gamma)
    //   (−proof_C,   vk_delta) →  e(−C, delta)
    // Product == 1 ⟺ valid Groth16 proof
    let mut pairs: Vec<(BytesN<64>, BytesN<128>)> = Vec::new(env);
    pairs.push_back((proof_a,      proof_b));
    pairs.push_back((neg_vk_alpha, vk_beta));
    pairs.push_back((neg_l,        vk_gamma));
    pairs.push_back((neg_proof_c,  vk_delta));

    let valid = env.crypto().bn254_pairing_check(pairs);

    if !valid {
        panic_with_error!(env, VerifierError::ProofInvalid);
    }
}

// ─────────────────────────────────────────────────────────────────────────────

fn parse_journal_and_build_record(env: &Env, journal: &Bytes, seal: &Bytes) -> ProofRecord {
    // The journal is JSON-encoded TradeProofOutput from the guest.
    // We do minimal parsing: find the key fields we store on-chain.
    // Using byte-level search to stay no_std compatible.
    let journal_bytes = journal.to_alloc_vec();

    // Parse the required fields from the JSON journal
    let valid         = json_bool(&journal_bytes, b"\"valid\"")
        .unwrap_or(false);
    let symbol        = json_str_field(&journal_bytes, b"\"symbol\"")
        .unwrap_or(b"UNKNOWN");
    let action        = json_str_field(&journal_bytes, b"\"action\"")
        .unwrap_or(b"UNKNOWN");
    let amount_f      = json_f64_field(&journal_bytes, b"\"amount_usdt\"")
        .unwrap_or(0.0);
    let rule_id       = json_str_field(&journal_bytes, b"\"rule_id\"")
        .unwrap_or(b"");
    let rule_name     = json_str_field(&journal_bytes, b"\"rule_name\"")
        .unwrap_or(b"");
    let drawdown_f    = json_f64_field(&journal_bytes, b"\"drawdown_pct\"")
        .unwrap_or(0.0);
    let dry_run       = json_bool(&journal_bytes, b"\"dry_run\"")
        .unwrap_or(true);
    let decided_at_ms = json_u64_field(&journal_bytes, b"\"decided_at_ms\"")
        .unwrap_or(0);

    if !valid {
        panic_with_error!(env, VerifierError::ProofInvalid);
    }

    // Receipt fingerprint — first 8 bytes of the seal (after the 4-byte selector)
    let fingerprint_arr: [u8; 8] = {
        let mut arr = [0u8; 8];
        for i in 0..8 {
            arr[i] = seal.get(4 + i as u32).unwrap_or(0);
        }
        arr
    };

    ProofRecord {
        index:               0,   // set by caller
        symbol:              String::from_str(env, core::str::from_utf8(symbol).unwrap_or("?")),
        action:              String::from_str(env, core::str::from_utf8(action).unwrap_or("?")),
        amount_usdt_cents:   (amount_f * 100.0) as i64,
        rule_id:             String::from_str(env, core::str::from_utf8(rule_id).unwrap_or("")),
        rule_name:           String::from_str(env, core::str::from_utf8(rule_name).unwrap_or("")),
        drawdown_bps:        (drawdown_f * 100.0) as i64,
        dry_run,
        decided_at_ms,
        verified_at_ledger:  0,   // set by caller
        receipt_fingerprint: BytesN::from_array(env, &fingerprint_arr),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Minimal no_std JSON field extractors
// ─────────────────────────────────────────────────────────────────────────────

fn json_bool(buf: &[u8], key: &[u8]) -> Option<bool> {
    let pos = find_subsequence(buf, key)? + key.len();
    let rest = buf.get(pos..)?;
    let colon = find_subsequence(rest, b":")?;
    let val_start = skip_whitespace(rest, colon + 1);
    if rest.get(val_start..)?.starts_with(b"true")  { return Some(true)  }
    if rest.get(val_start..)?.starts_with(b"false") { return Some(false) }
    None
}

fn json_str_field<'a>(buf: &'a [u8], key: &[u8]) -> Option<&'a [u8]> {
    let pos = find_subsequence(buf, key)? + key.len();
    let rest = buf.get(pos..)?;
    let colon = find_subsequence(rest, b":")?;
    let after = skip_whitespace(rest, colon + 1);
    if rest.get(after)? != &b'"' { return None; }
    let start = after + 1;
    let end = find_byte(rest.get(start..)?, b'"')? + start;
    rest.get(start..end)
}

fn json_f64_field(buf: &[u8], key: &[u8]) -> Option<f64> {
    let pos = find_subsequence(buf, key)? + key.len();
    let rest = buf.get(pos..)?;
    let colon = find_subsequence(rest, b":")?;
    let start = skip_whitespace(rest, colon + 1);
    let end = rest.get(start..)?.iter()
        .position(|&b| b == b',' || b == b'}' || b == b'\n')
        .map(|p| p + start)
        .unwrap_or(rest.len());
    let s = core::str::from_utf8(rest.get(start..end)?.trim_ascii()).ok()?;
    s.parse::<f64>().ok()
}

fn json_u64_field(buf: &[u8], key: &[u8]) -> Option<u64> {
    json_f64_field(buf, key).map(|f| f as u64)
}

fn find_subsequence(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

fn find_byte(haystack: &[u8], byte: u8) -> Option<usize> {
    haystack.iter().position(|&b| b == byte)
}

fn skip_whitespace(buf: &[u8], start: usize) -> usize {
    let mut i = start;
    while i < buf.len() && (buf[i] == b' ' || buf[i] == b'\t' || buf[i] == b'\n' || buf[i] == b'\r') {
        i += 1;
    }
    i
}

// ─────────────────────────────────────────────────────────────────────────────
// RISC Zero Groth16 Verification Key constants (BN254)
//
// These are the RISC Zero production Groth16 VK points for Stellar.
// Source: https://github.com/NethermindEth/stellar-risc0-verifier/blob/main/src/vk.rs
//
// !! Replace each placeholder with the real VK bytes from the above repo !!
// The placeholders below are all-zero — they will fail the pairing check.
// Once you copy the real VK bytes the verifier will work on testnet.
// ─────────────────────────────────────────────────────────────────────────────

fn vk_alpha_g1(env: &Env) -> BytesN<64> {
    // REPLACE: vk.alpha_g1 from NethermindEth stellar-risc0-verifier vk.rs
    BytesN::from_array(env, &[0u8; 64])
}

fn vk_beta_g2(env: &Env) -> BytesN<128> {
    // REPLACE: vk.beta_g2
    BytesN::from_array(env, &[0u8; 128])
}

fn vk_gamma_g2(env: &Env) -> BytesN<128> {
    // REPLACE: vk.gamma_g2
    BytesN::from_array(env, &[0u8; 128])
}

fn vk_delta_g2(env: &Env) -> BytesN<128> {
    // REPLACE: vk.delta_g2
    BytesN::from_array(env, &[0u8; 128])
}

fn vk_ic0_g1(env: &Env) -> BytesN<64> {
    // REPLACE: vk.ic[0]
    BytesN::from_array(env, &[0u8; 64])
}

fn vk_ic1_g1(env: &Env) -> BytesN<64> {
    // REPLACE: vk.ic[1]
    BytesN::from_array(env, &[0u8; 64])
}

fn vk_ic2_g1(env: &Env) -> BytesN<64> {
    // REPLACE: vk.ic[2]
    BytesN::from_array(env, &[0u8; 64])
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Env};

    #[test]
    fn test_initialise() {
        let env   = Env::default();
        let contract_id = env.register_contract(None, BinalystVerifier);
        let client = BinalystVerifierClient::new(&env, &contract_id);
        let admin  = Address::generate(&env);
        client.initialise(&admin);
        assert_eq!(client.admin(), admin);
        assert_eq!(client.proof_count(), 0);
    }

    #[test]
    fn test_json_bool_true() {
        let buf = br#"{"valid":true,"dry_run":false}"#;
        assert_eq!(json_bool(buf, b"\"valid\""),   Some(true));
        assert_eq!(json_bool(buf, b"\"dry_run\""), Some(false));
    }

    #[test]
    fn test_json_str_field() {
        let buf = br#"{"symbol":"BTC","action":"BUY"}"#;
        assert_eq!(json_str_field(buf, b"\"symbol\""), Some(b"BTC".as_ref()));
        assert_eq!(json_str_field(buf, b"\"action\""), Some(b"BUY".as_ref()));
    }

    #[test]
    fn test_json_f64_field() {
        let buf = br#"{"amount_usdt":1000.5,"drawdown_pct":4.75}"#;
        assert!((json_f64_field(buf, b"\"amount_usdt\"").unwrap() - 1000.5).abs() < 0.01);
        assert!((json_f64_field(buf, b"\"drawdown_pct\"").unwrap() - 4.75).abs() < 0.01);
    }

    #[test]
    fn test_placeholder_image_id_panics() {
        // Confirm that submitting a proof with the placeholder image_id
        // returns PlaceholderImageId error (not a cryptographic failure).
        // This guards against accidentally deploying with the placeholder.
        let env = Env::default();
        let contract_id = env.register_contract(None, BinalystVerifier);
        let client = BinalystVerifierClient::new(&env, &contract_id);
        let admin  = Address::generate(&env);
        client.initialise(&admin);

        let result = client.try_verify_trade_proof(
            &admin,
            &Bytes::from_array(&env, &[0u8; 300]),
            &Bytes::from_slice(&env, br#"{"valid":true}"#),
        );
        assert!(result.is_err());
    }
}
