// zk-host/src/main.rs
//
// Binalyst ZK host prover binary.
//
// Called by Next.js /api/zk/prove route:
//   proc = spawn("./target/release/binalyst-zk-host")
//   proc.stdin  ← JSON-encoded TradeProofInput
//   proc.stdout → JSON-encoded HostProverOutput
//
// What this does:
//   1. Reads TradeProofInput JSON from stdin
//   2. Creates a RISC Zero prover session with the guest ELF
//   3. Writes the input bytes to the guest's stdin (via env::write)
//   4. Runs the guest inside the zkVM
//   5. Extracts the receipt (seal + journal)
//   6. Writes HostProverOutput JSON to stdout
//
// Build:
//   cargo build --release -p binalyst-zk-host
//
// The binary lands at: target/release/binalyst-zk-host
// Set ZK_HOST_BIN=./target/release/binalyst-zk-host in .env.local

use std::io::{self, Read, Write};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, VerifierContext};
use serde::{Deserialize, Serialize};

// Generated by build.rs — contains BINALYST_ZK_GUEST_ELF + BINALYST_ZK_GUEST_ID
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

// ─────────────────────────────────────────────────────────────────────────────
// Output type written to stdout — consumed by /api/zk/prove route
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Serialize)]
struct HostProverOutput {
    /// Base64-encoded full RISC Zero receipt (for archiving/debugging)
    #[serde(rename = "receiptB64")]
    receipt_b64: String,

    /// Hex-encoded Groth16 seal — passed to Soroban contract as `seal: Bytes`
    #[serde(rename = "sealHex")]
    seal_hex: String,

    /// Hex-encoded journal bytes — passed to Soroban contract as `journal: Bytes`
    #[serde(rename = "journalHex")]
    journal_hex: String,

    /// Parsed TradeProofOutput from the journal — returned to the UI
    output: serde_json::Value,

    /// Elapsed proving time in milliseconds
    #[serde(rename = "elapsedMs")]
    elapsed_ms: u64,

    /// The image_id (hex) — useful for debugging / verifying against the contract
    #[serde(rename = "imageIdHex")]
    image_id_hex: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// main
// ─────────────────────────────────────────────────────────────────────────────

fn main() {
    // Read TradeProofInput JSON from stdin
    let mut input_json = String::new();
    io::stdin()
        .read_to_string(&mut input_json)
        .expect("Failed to read stdin");

    let input_bytes = input_json.trim().as_bytes().to_vec();

    let start = std::time::Instant::now();

    // Build executor environment — this is how we pass data to the guest
    let env = ExecutorEnv::builder()
        .write_slice(&input_bytes)
        .build()
        .expect("Failed to build ExecutorEnv");

    // Run the guest inside the zkVM and generate a Groth16 receipt
    // ProverOpts::groth16() produces a compact Groth16 proof (~260 byte seal)
    // suitable for on-chain verification via the Soroban BN254 host functions.
    //
    // For development/CI you can use ProverOpts::fast() which produces a
    // larger Stark proof faster — but it won't verify on-chain.
    // Set env var RISC0_DEV_MODE=1 to use the dev-mode mock prover (instant,
    // no real cryptography — for UI iteration only).
    let prover = default_prover();
    let receipt = prover
        .prove_with_opts(
            env,
            BINALYST_ZK_GUEST_ELF,
            &ProverOpts::groth16(),
        )
        .expect("Proving failed")
        .receipt;

    // Verify the receipt locally before returning (sanity check)
    receipt
        .verify(BINALYST_ZK_GUEST_ID)
        .expect("Receipt verification failed — guest ELF or image_id mismatch");

    let elapsed_ms = start.elapsed().as_millis() as u64;

    // ── Extract seal ─────────────────────────────────────────────────────────
    // The Groth16 receipt seal is the compact proof bytes.
    // risc0_zkvm serialises the InnerReceipt as bincode — we need the raw seal.
    let seal_bytes = extract_groth16_seal(&receipt)
        .expect("Failed to extract Groth16 seal — was ProverOpts::groth16() used?");

    // ── Extract journal ───────────────────────────────────────────────────────
    let journal_bytes = receipt.journal.bytes.clone();

    // ── Parse journal → TradeProofOutput ─────────────────────────────────────
    let output: serde_json::Value = serde_json::from_slice(&journal_bytes)
        .expect("Failed to parse journal as JSON — guest did not commit valid JSON");

    // ── Serialise the full receipt for archiving ──────────────────────────────
    let receipt_bytes = bincode::serialize(&receipt)
        .expect("Failed to serialise receipt");
    let receipt_b64 = base64_encode(&receipt_bytes);

    // ── image_id as hex ───────────────────────────────────────────────────────
    let image_id_hex = BINALYST_ZK_GUEST_ID
        .iter()
        .map(|w| format!("{:08x}", w))
        .collect::<Vec<_>>()
        .join("");

    // ── Write output to stdout ────────────────────────────────────────────────
    let out = HostProverOutput {
        receipt_b64,
        seal_hex:    hex_encode(&seal_bytes),
        journal_hex: hex_encode(&journal_bytes),
        output,
        elapsed_ms,
        image_id_hex,
    };

    let out_json = serde_json::to_string(&out)
        .expect("Failed to serialise HostProverOutput");

    // Write to stdout — the Next.js route reads this
    io::stdout()
        .write_all(out_json.as_bytes())
        .expect("Failed to write to stdout");
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Extract the raw Groth16 seal bytes from a RISC Zero receipt.
/// The receipt's inner variant must be Groth16 (use ProverOpts::groth16()).
fn extract_groth16_seal(receipt: &risc0_zkvm::Receipt) -> Option<Vec<u8>> {
    use risc0_zkvm::InnerReceipt;
    match &receipt.inner {
        InnerReceipt::Groth16(groth16) => {
            // The Groth16 receipt encodes: [4-byte selector][A G1 64b][B G2 128b][C G1 64b][pub inputs...]
            // risc0-zkvm provides seal() on the Groth16 receipt
            Some(groth16.seal.clone())
        }
        _ => None,
    }
}

/// Simple hex encoding without external deps
fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Simple base64 encoding (RFC 4648, no padding trimming needed for our use)
fn base64_encode(bytes: &[u8]) -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((bytes.len() + 2) / 3 * 4);
    for chunk in bytes.chunks(3) {
        let b0 = chunk[0] as usize;
        let b1 = chunk.get(1).copied().unwrap_or(0) as usize;
        let b2 = chunk.get(2).copied().unwrap_or(0) as usize;
        let n  = (b0 << 16) | (b1 << 8) | b2;
        out.push(ALPHABET[(n >> 18) & 0x3F] as char);
        out.push(ALPHABET[(n >> 12) & 0x3F] as char);
        out.push(if chunk.len() > 1 { ALPHABET[(n >> 6) & 0x3F] as char } else { '=' });
        out.push(if chunk.len() > 2 { ALPHABET[n & 0x3F]        as char } else { '=' });
    }
    out
}
