// zk-host/src/main.rs — REWRITTEN (Session P2)
//
// Generates a RISC Zero Groth16 proof and outputs exactly the three values
// the NethermindEth Stellar verifier router expects:
//   seal           — via risc0_ethereum_contracts::encode_seal(&receipt)
//   image_id       — the guest's compile-time ID (BINALYST_ZK_GUEST_ID)
//   journal_digest — sha256(receipt.journal)
//
// This matches docs/verifying-risc0-proofs.md exactly:
//   https://github.com/NethermindEth/stellar-risc0-verifier/blob/main/docs/verifying-risc0-proofs.md
//
// Previously (Session P / PATCH2) we invented our own seal byte-layout and
// tried to hand-roll BN254 pairing verification in Soroban. That is wrong —
// the router's deployed Groth16Verifier already does this. Our only job is
// to produce (seal, image_id, journal_digest) in the format it expects.
//
// Build:
//   cargo build --release -p binalyst-zk-host
//
// Run (called by Next.js /api/zk route):
//   echo '<TradeProofInput JSON>' | ./target/release/binalyst-zk-host

use std::io::{self, Read, Write};
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts};
use risc0_ethereum_contracts::encode_seal;
use sha2::{Digest, Sha256};
use serde::Serialize;

// Generated by build.rs (risc0_build::embed_methods) —
// contains BINALYST_ZK_GUEST_ELF + BINALYST_ZK_GUEST_ID
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

#[derive(Serialize)]
struct HostProverOutput {
    /// Hex-encoded Groth16 seal, in the router's expected format
    /// (encode_seal handles the routing-selector prefix internally).
    #[serde(rename = "sealHex")]
    seal_hex: String,

    /// Hex-encoded 32-byte image_id — identifies which guest program ran.
    #[serde(rename = "imageIdHex")]
    image_id_hex: String,

    /// Hex-encoded 32-byte journal digest = sha256(journal_bytes).
    /// This is what gets passed to router.verify(), NOT the raw journal.
    #[serde(rename = "journalDigestHex")]
    journal_digest_hex: String,

    /// Raw journal bytes as JSON (so the caller can parse TradeProofOutput
    /// without needing to know the digest pre-image separately).
    output: serde_json::Value,

    #[serde(rename = "elapsedMs")]
    elapsed_ms: u64,
}

fn main() {
    let mut input_json = String::new();
    io::stdin().read_to_string(&mut input_json).expect("Failed to read stdin");
    let input_bytes = input_json.trim().as_bytes().to_vec();

    let start = std::time::Instant::now();

    let env = ExecutorEnv::builder()
        .write_slice(&input_bytes)
        .build()
        .expect("Failed to build ExecutorEnv");

    // Groth16 proof — required for on-chain verification (compact, ~260 bytes)
    let prover     = default_prover();
    let prove_info = prover
        .prove_with_opts(env, BINALYST_ZK_GUEST_ELF, &ProverOpts::groth16())
        .expect("Proving failed");
    let receipt = prove_info.receipt;

    // Sanity-check locally before returning
    receipt
        .verify(BINALYST_ZK_GUEST_ID)
        .expect("Local receipt verification failed");

    let elapsed_ms = start.elapsed().as_millis() as u64;

    // ── Encode exactly as the NethermindEth docs specify ──────────────────────
    let seal = encode_seal(&receipt).expect("encode_seal failed");
    let journal_digest: [u8; 32] = Sha256::digest(&receipt.journal.bytes).into();
    let image_id: [u8; 32] = BINALYST_ZK_GUEST_ID;

    // Parse the journal as JSON so the caller gets TradeProofOutput directly
    let output: serde_json::Value = serde_json::from_slice(&receipt.journal.bytes)
        .expect("Guest journal was not valid JSON");

    let out = HostProverOutput {
        seal_hex:            hex::encode(&seal),
        image_id_hex:        hex::encode(image_id),
        journal_digest_hex:  hex::encode(journal_digest),
        output,
        elapsed_ms,
    };

    let out_json = serde_json::to_string(&out).expect("Failed to serialise output");
    io::stdout().write_all(out_json.as_bytes()).expect("Failed to write stdout");
}
